name = "Ba'Y J'Kaara Armoury";
actionName = "Workshop";
author = "JCaleb2014";
action = "https://steamcommunity.com/profiles/76561198131886488/myworkshopfiles/?appid=107410";
description = "Ba'Y J'Kaara Armoury Mod";
overview = "Retextures of Tau Assets, Imperium and Adeptus Mechanicus";
logo = "BaY_JKaara_Armoury\bjk_meta\logo.paa";
logoSmall = "BaY_JKaara_Armoury\bjk_meta\logosmall.paa";
logoOver = "BaY_JKaara_Armoury\bjk_meta\logo.paa";
picture = "BaY_JKaara_Armoury\bjk_meta\picture.paa";